### ISSUE TITLE
Redesign the <select> tag

### ISSUE THREAD

**Issue by jyotman** [jyotman94/addypython#1]
The form located at [this](http://www.euromotocorp.in/contact/) page has a `<select>`  HTML tag which doesn't look good with the other material design components taken from [getmdl.io](http://getmdl.io) which doesn't have a selector component yet.

A better looking `<select>` component which goes with the theme would look great.

These are the respective [HTML](https://github.com/jyotman94/euromotocorp.in/blob/master/wheels/templates/wheels/name.html) and [python-form](https://github.com/jyotman94/euromotocorp.in/blob/master/wheels/forms.py) file.

**Comment by divayprakash** [comment]
@jyotman94 Can I take this up?

**Comment by jyotman94** [comment]
Sure :)

**Comment by blake-mealey** [comment]
Hey there! I'd be willing to attempt this. I was looking around and found [this MDL-style select tag styling](https://github.com/MEYVN-digital/mdl-selectfield). Would that fit your requirements?

**Comment by jyotman** [comment]
Hey this looks great! Go ahead :)

**Comment by blake-mealey** [comment]
Can you give me some quick instructions to get the site running so I can see if my changes work?

**Comment by jyotman** [comment]
@blake-mealey I've updated the README.md with the installation instructions. Please have a look.

Also take a pull as I've added the settings.py file.

**Comment by blake-mealey** [comment]
Thanks! Sorry I was busy all week, but I'll take a crack at this now :)

**Comment by blake-mealey** [comment]
So I ran the setup instructions and ended up with this error page:
[error.zip](https://github.com/jyotman94/euromotocorp.in/files/560713/error.zip)

**Comment by jyotman** [comment]
Hey, I saw the error. It seems to be a change in Django version 1.10. Can you please try again with Django 1.9?
Just write `pip install django==1.9` instead of just django.

I'm pretty sure that would solve the issue :)
